### ISSUE TITLE
Feedback for Pull Dog

### ISSUE THREAD

**Issue by ffMathy** [yunfandev/InteropApp#2]
Hi @yunfandev!

Sorry for writing here, I didn't know where else to reach out. 

You recently tried Pull Dog (a GitHub app that I built), but uninstalled it for a repository. 

Feedback is super hard to come by for indie hackers, so I was wondering if you could leave some feedback? 

Was it hard to get working?

**Comment by yunfandev** [comment]
I haven't started using PullDog 😂😂😂

**Comment by ffMathy** [comment]
Ah okay - my bad! :sweat_smile:

If you do, let me know if there's anything I can help with!
