### ISSUE TITLE
BadImageFormatException

### ISSUE THREAD

**Issue by Weijee** [yunfandev/InteropApp#3]
### Hello, I got an exception below when i was tring to run your demo.
![image](https://user-images.githubusercontent.com/13539500/116676869-1a0daa80-a9da-11eb-9bad-8aeec6d485a9.png)

### This is my project configuration, and i did not do any changes after clone this demo. 
![image](https://user-images.githubusercontent.com/13539500/116676932-2c87e400-a9da-11eb-8fbf-c631d6f4555a.png)
![image](https://user-images.githubusercontent.com/13539500/116676960-3578b580-a9da-11eb-8f01-f800b699d898.png)

**Comment by yunfandev** [comment]
@Weijee Only x64 is supported

https://github.com/yunfandev/InteropApp/blob/0420c4a1c6594f6cf466f297dcae4185bbc98dd3/Dockerfile#L10

**Comment by Weijee** [comment]
@yunfandev Thank you for your kindly reply, it works!  
But I ran to a new issue. The ConsoleApp works well by referencing the InteropLib project directly! When I reference the InteropLib.dll instead of the project, the same exception occurs!

**Comment by yunfandev** [comment]
@Weijee Please make sure that the active platform of your other projects is also set to x64 instead of anycpu.

![image](https://user-images.githubusercontent.com/8027453/117278528-6dc53b80-ae93-11eb-8db2-e4e651146b71.png)
